### ISSUE TITLE
CreadorEncuestaNoPuedeVotarException deberia heredar de RuntimeException

### ISSUE THREAD

**Issue by maurociancio** [tpalge/nuevo-foro-fiuba#1]
las excepciones que heredan de exception se llaman checked y no son muy utilizadas. Tambien trae problemas con spring y la transaccionalidad. 
https://www.catalysts.cc/wissenswertes/spring-transactional-rollback-on-checked-exceptions/

**Comment by maurociancio** [comment]
idem PromedioInsuficienteException

**Comment by maurociancio** [comment]
No pongan esas clases en la carpeta domain. Hace que esas clases sean persistentes.

**Comment by Mariano95** [comment]
Corregido
