### ISSUE TITLE
No usen Ids para comparar en el dominio

### ISSUE THREAD

**Issue by maurociancio** [tpalge/nuevo-foro-fiuba#3]
Boolean esDueñoDeLaPublicacion(Publicacion publicacion){
		(publicacion.getUsuarioCreador().getId() == this.id)
	}

**Comment by maurociancio** [comment]
Tienen que usar el operador == (que invoca al equals) sobre las entidades.
Si tienen problemas van a tener que redefinir el equals y hashcode()

**Comment by Mariano95** [comment]
Listo, definiendo equalsAndHashcode pudimos deshacernos de los .id en el dominio.
